server:
  port: 9000
spring:
  application:
    name: s3-services/
  dataSource:
    url: "jdbc:postgresql://3.132.57.72:5432/naranjos2"
    username: "postgres"
    password: "N4r4nj0s*."
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 80000
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      pool-name: HikariPool
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIAXDX6W4JQDZVJNJPO
      secret-key: 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
    region: us-east-2
    bucket: recnar/mantenimiento
    url: "https://recnar.s3.us-east-2.amazonaws.com/"
    uri: "s3://"
    stack:
      auto: false